#!/usr/bin/env sh
# YABAI STUFF

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

## global settings
yabai -m config external_bar off
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse on
## New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
## floating windows are always on top (default: off)
yabai -m config window_topmost on
## example: show shadows only for floating windows
yabai -m config window_shadow off
yabai -m config window_opacity off
# yabai -m config window_opacity_duration 0.0
# yabai -m config active_window_opacity 1.0
# yabai -m config normal_window_opacity 0.90
yabai -m config window_border off # (on | off)
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555555
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config auto_balance on
yabai -m config split_ratio 0.50
## set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier fn
# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action stack

# general space settings
# bsp or float (default: bsp)
yabai -m config layout bsp
## Change how yabai looks
yabai -m config top_padding 4
yabai -m config bottom_padding 4
yabai -m config left_padding 4
yabai -m config right_padding 4
yabai -m config window_gap 5

# My custom space names for my 3 monitor setup. These names are used in some of my scripts.
# yabai -m space 1 --label one
# yabai -m space 2 --label two
# yabai -m space 3 --label three
# yabai -m space 4 --label four
# yabai -m space 5 --label five
# yabai -m space 6 --label six
# yabai -m space 9 --label nine

# # add 20 padding to the top and 0 padding to the bottom of every space located on the main display
yabai -m config external_bar all:0:0
# yabai -m config external_bar main:20:0
# add 20 padding to the top and bottom of all spaces regardless of the display it belongs to
# yabai -m config external_bar all:20:20

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=off layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Calculator$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^AppCleaner$" sticky=off layer=above manage=off
yabai -m rule --add app="^iStat Menus$" sticky=off layer=above manage=off
yabai -m rule --add app="^WeChat$" sticky=off manage=off
yabai -m rule --add app="^Spotify$" sticky=off manage=off
yabai -m rule --add app="^Calendar$" sticky=off manage=off
yabai -m rule --add app="^QQ$" sticky=off manage=off
yabai -m rule --add app="^App Store$" sticky=off manage=off
yabai -m rule --add app="^Notes$" sticky=off manage=off
yabai -m rule --add app="^Reminders$" sticky=off manage=off
yabai -m rule --add app="^iTerm2$" sticky=off manage=off
yabai -m rule --add app="^Messages$" sticky=off manage=off
yabai -m rule --add app="^IntelliJ IDEA$" sticky=off manage=off
yabai -m rule --add app="^Music$" sticky=off manage=off
yabai -m rule --add app="^Input Source Pro$" sticky=off manage=off

# find ~/Library/Parallels/Applications\ Menus/ -maxdepth 3 -type f | awk -F'/' '{ print $NF; }' | awk '{$1=$1};1' | sort | uniq | tr "\n" "\0" | xargs -0 -I{} yabai -m rule --add app="^{}\$" title=".*" manage=on

## general space settings
# yabai -m config focused_border_skip_floating  1
# yabai -m config --space 3 layout             float

# signals
# yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# yabai -m signal --add event=space_changed action="yabai -m window --focus $(yabai -m query --windows --window | jq ".id")"
# yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# testing signals
# yabai -m signal --add event=window_destroyed action="terminal-notifier -message 'window_destroyed'"
# yabai -m signal --add event=application_terminated action="terminal-notifier -message 'application_terminated'"
# yabai -m signal --add event=window_focused action="yabai -m window --toggle zoom-fullscreen"

## If I close the active window, focus on any other visible window.
yabai -m signal --add event=window_destroyed action="bash ~/.config/yabai/scripts/windowFocusOnDestroy.sh"

# yabai -m signal --add event=space_changed action="export CUR_ACTIVE_APP=\"iTerm2\""

echo "yabai configuration loaded.."

#END
yabai -m config external_bar all:0:0 \
  mouse_follows_focus off \
  focus_follows_mouse off \
  window_zoom_persist off \
  window_placement second_child \
  window_shadow float \
  window_opacity on \
  window_opacity_duration 0.2 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.8 \
  window_animation_duration 0.5 \
  window_animation_easing ease_out_quint \
  insert_feedback_color 0xff9dd274 \
  split_ratio 0.50 \
  auto_balance off \
  auto_padding on \
  mouse_modifier fn \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap \
  \
  top_padding 8 \
  bottom_padding 8 \
  left_padding 8 \
  right_padding 8 \
  window_gap 10
